# Generated by Django 3.1.7 on 2021-06-04 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tenis', 'Tenis'), ('moletom', 'Moletom'), ('Jeans', 'Jeans')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Feminine'), ('M', 'Male'), ('U', 'Unisex')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=False)),
                ('amount', models.IntegerField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barb.category')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barb.gender')),
            ],
        ),
    ]
