# Generated by Django 3.1.7 on 2021-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
