# Generated by Django 3.1.7 on 2021-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0003_auto_20210808_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendido',
            field=models.IntegerField(default=False),
        ),
    ]
