# Generated by Django 3.1.7 on 2021-10-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0004_product_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
