# Generated by Django 3.1.7 on 2021-07-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0002_product_upload'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='barb.product'),
        ),
    ]
