# Generated by Django 3.1.7 on 2021-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210729_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qnty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(default=1)),
                ('cart', models.ManyToManyField(blank=True, to='cart.Cart')),
            ],
        ),
    ]
