# Generated by Django 3.1.7 on 2021-08-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_qnty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnty',
            name='cart',
        ),
        migrations.AddField(
            model_name='qnty',
            name='cart',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
    ]
