# Generated by Django 3.1.7 on 2021-08-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0004_product_vendido'),
        ('cart', '0004_auto_20210813_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnty',
            name='products',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='barb.product'),
            preserve_default=False,
        ),
    ]
