# Generated by Django 3.1.7 on 2021-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_qnty_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnty',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
