# Generated by Django 3.1.7 on 2021-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_qnty_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnty',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
