# Generated by Django 3.1.7 on 2021-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210816_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnty',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
